INSERT INTO USERS(ID,USERNAME, PASSWORD, EMAIL, INFO) VALUES (1, 'jose', '{argon2}$argon2id$v=19$m=4096,t=3,p=1$zlLqZ2hkjNUgqn2PVUx0/g$hr3skZ96zR/tHJPQOlGF+ds0ZcsNGBEuNeG30jn8WbM', 'deratoy543@healteas.com', null);

INSERT INTO DEVICES(ID,SERIAL,USER_ID) VALUES (1, '1234',1);

INSERT INTO SENSORS(ID,TYPE,DEVICE_ID) VALUES (1, 0,1);
INSERT INTO SENSORS(ID,TYPE,DEVICE_ID) VALUES (2, 1,1);
INSERT INTO SENSORS(ID,TYPE,DEVICE_ID) VALUES (3, 2,1);

INSERT INTO SENSOR_STATUS(ID,VALUE,SENSOR_ID) VALUES (1, '-23.6211644',1);
INSERT INTO SENSOR_STATUS(ID,VALUE,SENSOR_ID) VALUES (2, '-46.6527874',2);
INSERT INTO SENSOR_STATUS(ID,VALUE,SENSOR_ID) VALUES (3, '23.5',3);
